### ISSUE TITLE
tox -e 27 failing

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/QrScan#12]
Running tests via `tox` is failing.
```
tox -e py27
py27 installed: certifi==2018.4.16,chardet==3.0.4,contextlib2==0.5.5,Cython==0.26.1,decorator==4.3.0,docutils==0.14,idna==2.6,Kivy==1.10.1.dev0,Kivy-Garden==0.1.4,kivymd==0.1.2,numpy==1.14.0,Pillow==5.0.0,Pygments==2.2.0,raven==6.6.0,requests==2.18.4,six==1.11.0,urllib3==1.2
2,validators==0.12.1,zbar==0.10
py27 runtests: PYTHONHASHSEED='2495260927'
py27 runtests: commands[0] | python -m unittest discover --start-directory=src/
[INFO   ] [Logger      ] Record log in /home/andre/.kivy/logs/kivy_18-05-23_12.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-Unknown, 20180523
[INFO   ] [Python      ] v2.7.15rc1 (default, Apr 15 2018, 21:51:34)
[GCC 7.3.0]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Clipboard   ] Provider: sdl2(['clipboard_dbusklipper', 'clipboard_gtk3', 'clipboard_xclip', 'clipboard_xsel'] ignored)
[CRITICAL] [Cutbuffer   ] Unable to find any valuable Cutbuffer provider.
xclip - OSError: [Errno 2] No such file or directory
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivy/core/clipboard/clipboard_xclip.py", line 17, in <module>
    p = subprocess.Popen(['xclip', '-version'], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception

xsel - OSError: [Errno 2] No such file or directory
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivy/core/clipboard/clipboard_xsel.py", line 16, in <module>
    p = subprocess.Popen(['xsel'], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)                                             
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception

[INFO   ] [KivyMD      ] KivyMD version: 0.1.2
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
error: XDG_RUNTIME_DIR not set in the environment.
[CRITICAL] [Window      ] Unable to find any valuable Window provider.
egl_rpi - ImportError: cannot import name bcm
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivy/core/window/window_egl_rpi.py", line 12, in <module>
    from kivy.lib.vidcore_lite import bcm, egl

sdl2 - RuntimeError: No available video device
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivy/core/__init__.py", line 67, in core_select_lib
    cls = cls()
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 140, in __init__
    super(WindowSDL, self).__init__()
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivy/core/window/__init__.py", line 949, in __init__
    self.create_window()
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 269, in create_window
    self.fullscreen, resizable, state)
  File "kivy/core/window/_window_sdl2.pyx", line 84, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 57, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

x11 - ImportError: No module named window_x11
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)

[CRITICAL] [App         ] Unable to get a Window, abort.
E
======================================================================
ERROR: tests.test_main (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_main
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/andre/workspace/QrScan/src/tests/test_main.py", line 6, in <module>
    from main import CodeType
  File "/home/andre/workspace/QrScan/src/main.py", line 13, in <module>
    from kivymd.theming import ThemeManager
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivymd/theming.py", line 13, in <module>
    from kivymd.material_resources import FONTS, DEVICE_TYPE
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivymd/material_resources.py", line 23, in <module>
    MAX_NAV_DRAWER_WIDTH = dp(400)
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivy/metrics.py", line 136, in dp
    return dpi2px(value, 'dp')
  File "kivy/properties.pyx", line 291, in kivy.properties.dpi2px
  File "kivy/properties.pyx", line 296, in kivy.properties.dpi2px
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivy/utils.py", line 496, in __get__
    retval = self.func(inst)
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivy/metrics.py", line 174, in dpi
    EventLoop.ensure_window()
  File "/home/andre/workspace/QrScan/.tox/py27/local/lib/python2.7/site-packages/kivy/base.py", line 125, in ensure_window
    sys.exit(1)
SystemExit: 1


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
ERROR: InvocationError: '/home/andre/workspace/QrScan/.tox/py27/bin/python -m unittest discover --start-directory=src/'
_____________________________________________________________________________________________________________________________________ summary _____________________________________________________________________________________________________________________________________
ERROR:   py27: commands failed
```

However running them manually works:
```
python -m unittest discover --start-directory=src/
[INFO   ] [Logger      ] Record log in /home/andre/.kivy/logs/kivy_18-05-23_13.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-Unknown, 20180523
[INFO   ] [Python      ] v2.7.15rc1 (default, Apr 15 2018, 21:51:34)
[GCC 7.3.0]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Clipboard   ] Provider: sdl2(['clipboard_dbusklipper', 'clipboard_gtk3', 'clipboard_xclip', 'clipboard_xsel'] ignored)
[CRITICAL] [Cutbuffer   ] Unable to find any valuable Cutbuffer provider.
xclip - OSError: [Errno 2] No such file or directory
  File "/home/andre/workspace/QrScan/venv/local/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/andre/workspace/QrScan/venv/local/lib/python2.7/site-packages/kivy/core/clipboard/clipboard_xclip.py", line 17, in <module>
    p = subprocess.Popen(['xclip', '-version'], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception

xsel - OSError: [Errno 2] No such file or directory
  File "/home/andre/workspace/QrScan/venv/local/lib/python2.7/site-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/andre/workspace/QrScan/venv/local/lib/python2.7/site-packages/kivy/core/clipboard/clipboard_xsel.py", line 16, in <module>
    p = subprocess.Popen(['xsel'], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception

[INFO   ] [KivyMD      ] KivyMD version: 0.1.2
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 18.0.0-rc5>
[INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) >
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
..
----------------------------------------------------------------------
Ran 2 tests in 0.001s

OK
```

**Comment by AndreMiras** [comment]
We may remove `tox` and replace it by `Makefile` completely. Tox makes sense for library as we're testing multiple Python versions, but not much for a software.
